name: Beta Test
on:
  release:
    types: [created]
env:
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
jobs:
  beta_test:
    name: "Beta Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sfdx
        run: |
          mkdir sfdx
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
          ./sfdx/install
          echo ${{ secrets.SFDX_AUTH_URL }} > sfdx_auth
          sfdx force:auth:sfdxurl:store -f sfdx_auth -d
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Determine Python Version
        id: python-version
        run: |
          echo "::set-output name=ver::$(python --version)"
      - uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-${{ steps.python-version.outputs.ver }}-${{ hashFiles('requirements.txt') }}
      - name: Install CumulusCI
        run: |
          python3 -m venv venv
          venv/bin/pip install -r requirements.txt
      - name: Build Org and Execute Tests
        run: |
          venv/bin/cci flow run ci_beta --org beta
      - name: Store Test Results
        uses: actions/upload-artifact@v1
        with:
          name: apex_test_results.xml
          path: test_results.xml
      - name: Delete Scratch Org
        if: ${{ always() }}
        run: |
          venv/bin/cci org scratch_delete beta
